#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Ready!?😁🚀 🏗️👷 Styling, testing and building your project before committing'

npm run check-format ||
(
    echo '🤢🤢 NO NO !! you need to reformat some code styles. 🤢🤢
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    npm run format;
    git add $(git diff --name-only --cached | grep -E '\.(js|jsx|ts|tsx|scss|css)$');
)

npm run check-lint ||
(
        echo '😤🏀👋😤 Aahh!! you have eslint errors 😤🏀👋😤
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
)

npm run check-types ||
(
    echo '🤡😂❌🤡 Ooops!! Type check failed. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'